# Generated by Django 4.2.4 on 2023-08-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_enseignant_etudiant_remove_user_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_de_naissance',
            field=models.DateField(null=True, verbose_name='Date de Naissance'),
        ),
    ]
