# Generated by Django 4.2.4 on 2023-08-26 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0005_student_teacher_remove_etudiant_user_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='teacher',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
