# Generated by Django 4.2.4 on 2023-08-26 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0007_remove_user_is_parent_student_is_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='student',
            new_name='teacher',
        ),
    ]
