# Generated by Django 4.2.4 on 2023-08-27 10:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0008_rename_student_teacher_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_teacher',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='date',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='user',
            name='date_de_naissance',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de Naissance'),
        ),
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.IntegerField(verbose_name="Numero de l'étudiant"),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='number',
            field=models.IntegerField(verbose_name="Numero de l'enseignant"),
        ),
    ]
