# Generated by Django 4.2.4 on 2023-08-27 10:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentification', '0009_remove_student_date_remove_student_is_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=3000)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.teacher')),
                ('etudiants', models.ManyToManyField(related_name='CoursAlloue', to='authentification.student')),
            ],
        ),
        migrations.CreateModel(
            name='FichierDeSoumission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=300)),
                ('fichier', models.FileField(upload_to='course_files/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'doc', 'ppt', 'pptx', 'zip', 'rar', '7zip'])])),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=3000)),
                ('fichier', models.FileField(upload_to='course_files/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'doc', 'ppt', 'pptx', 'zip', 'rar', '7zip'])])),
                ('statut', models.CharField(choices=[('En Cours', 'En Cours'), ('Soumis', 'Soumis'), ('Corrigé', 'Corrigé'), ('Traité', 'Traité'), ('Archivé', 'Archivé')], default='En Cours', max_length=3000)),
                ('mariere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cours')),
            ],
        ),
    ]
